### ISSUE TITLE
undefined reference to DiscoverSched::DiscoverSched in IcecreamMonitor::slotCheckScheduler

### ISSUE THREAD

**Issue by den4ix** [icecc/icemon#28] opened 2017-01-28 12:26 UTC
While building icemon on Gentoo machine either with gcc-4.9.3 or gcc-5.4.0 I experience linking issue:
```
CMakeFiles/icemon.dir/icecreammonitor.cc.o: In function `IcecreamMonitor::slotCheckScheduler()':
icecreammonitor.cc:(.text+0x967): undefined reference to `DiscoverSched::DiscoverSched(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
collect2: error: ld returned 1 exit status
src/CMakeFiles/icemon.dir/build.make:654: recipe for target 'src/icemon' failed
make[2]: *** [src/icemon] Error 1
CMakeFiles/Makefile2:120: recipe for target 'src/CMakeFiles/icemon.dir/all' failed
make[1]: *** [src/CMakeFiles/icemon.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
[log_icemon_build.txt](https://github.com/icecc/icemon/files/736876/log_icemon_build.txt)

**Comment by krf** [comment] 2017-04-03 07:59
Still a problem? Did you try a complete fresh build?

**Comment by krf** [comment] 2017-04-06 21:07
This is a duplicate of #24. Please make sure you build at least 3.0.1.

Please report back if the problem persists.

**Closed by krf** 2017-04-06 21:07 UTC
